const letterList = document.querySelectorAll('.greeting__letter');
const menuBtn = document.querySelector('.btn__menu');
const header = document.querySelector('.header');
const menuLinks = document.querySelectorAll('.header__link');
const background = document.querySelector('.background');
const boxBottom = document.querySelector('.box_bottom');
const boxCenter = document.querySelector('.box_center');
const boxtop = document.querySelector('.box_top');
const boxList = document.querySelectorAll('.box');
const cardsSkillsList = document.querySelectorAll('.skills__card');
const mousePosInCard = {};
const mousePos = {};
let timer;
const popup = document.querySelector('.popup');
const btnClose = document.querySelector('.btn__close');
const typeProjects = Array.from(document.querySelectorAll('.greeting__li'));
const projectTemplate = document.querySelector('#project').content;
const containerProjects = document.querySelector('#projects');
const projectsArr = [
  {
    id: 0,
    type: 'Pet/commercial projects',
    name: 'Landing Page CyberGid',
    about: 'Страница рассказывает о приложении-аудиогиде CyberGid. Выполнена адаптивная и кроссбраузерная вёрстка, настроены переходы по ссылкам, слайдер для карточек.',
    img_bg: './images/flowers/pic4.jpg',
    img_project: './images/projects/cybergid.png',
    gif: './images/gif/cybergid_landing.gif',
    link_github_page: 'https://gutmalina.github.io/cybergid-landing/',
    link_github_code: 'https://github.com/gutmalina/cybergid-landing',
  },
  {
    id: 1,
    type: 'Pet/commercial projects',
    name: 'Pet Project Simple-reports',
    about: 'Проект создан группой junior разработчиков и направлен на сбор и анализ данных для маркетинговых исследований. Находится на стадии разработки.',
    img_bg: './images/flowers/pic9.jpg',
    img_project: './images/projects/simple-reports.png',
    gif: './images/gif/simple_reports.gif',
    link_github_page: 'https://gutmalina.github.io/simple-reports/',
    link_github_code: 'https://github.com/gutmalina/simple-reports',

  },
  {
    id: 2,
    type: 'Pet/commercial projects',
    name: 'Web site АиБ Цифровизация',
    about: 'Коммерческая разработка frontend части web-сайта для компании АиБ Цифровизация. Выполнена адаптивная и кроссбраузерная вёрстка, настроена валидация и отправка данных на сервер, фильтры и слайдер карточек.',
    img_bg: './images/flowers/pic6.jpg',
    img_project: './images/projects/aib.png',
    gif: './images/gif/aib.gif',
    link_github_page: 'https://gutmalina.github.io/aib/',
    link_github_code: 'https://github.com/gutmalina/aib',
  },
  {
    id: 3,
    type: 'Test task',
    name: 'WhatsApp web',
    about: 'Пользовательский интерфейс для отправки и получений сообщений WhatsApp. Использован прототип сайта https://web.whatsapp.com/ Необходимы учетные данные из системы GREEN-API (idInstance, apiTokenInstance)',
    img_bg: './images/flowers/pic7.jpg',
    img_project: './images/projects/green-api.png',
    gif: './images/gif/whatsapp.gif',
    link_github_page: 'https://gutmalina.github.io/green-api/',
    link_github_code: 'https://github.com/gutmalina/green-api/',
  },
  {
    id: 4,
    type: 'Test task',
    name: 'React Leaflet',
    about: 'Приложение React отображающее точки маршрута в виде маркеров на карте Leaflet. Между точек формируется оптимальный маршрут и отображается в виде полилиний, полученных из сервиса построения треков по дорогам OSRM',
    img_bg: './images/flowers/pic8.jpg',
    img_project: './images/projects/leaflet.png',
    gif: './images/gif/leaflet.gif',
    link_github_page: 'https://gutmalina.github.io/route-display/',
    link_github_code: 'https://github.com/gutmalina/route-display/',
  },
  {
    id: 5,
    type: 'Test task',
    name: 'Landing Page DELL',
    about: 'Страница компании DELL создана в рамках тестового задания. Выполнена адаптивная и кроссбраузерная вёрстка 375px-1920px, создано выпадающее меню при наведение и клике на бургер в мобильной версии, выполнена минимальная валидация данных в форме.',
    img_bg: './images/flowers/pic5.jpg',
    img_project: './images/projects/dell.png',
    gif: './images/gif/dell_landing.gif',
    link_github_page: 'https://gutmalina.github.io/dell-landing/',
    link_github_code: 'https://github.com/gutmalina/dell-landing',
  },
  {
    id: 6,
    type: 'Learn projects',
    name: 'Burger designer',
    about: 'Онлайн-конструктор бургеров позволяет создать свой собственный уникальный бургер из списка представленных ингредиентов. Доступны регистрация, сброс пароля, заказ бургера, просмотр прошлых заказов, изменение учетных данных. Необходима авторизация (указать email, без подтверждения)',
    img_bg: './images/flowers/pic1.jpg',
    img_project: './images/projects/react-burger.png',
    gif: './images/gif/burger.gif',
    link_github_page: 'https://gutmalina.github.io/react-burger/',
    link_github_code: 'https://github.com/gutmalina/react-burger',
  },
  {
    id: 7,
    type: 'Learn projects',
    name: 'Social network "Mesto"',
    about: 'Социальная сеть для обмена фотографиями. Доступны добавление и удаление фотографий, регистрация, изменение учетных данных, установка/снятие лайка. Необходима авторизация (указать email, без подтверждения)',
    img_bg: './images/flowers/pic2.jpg',
    img_project: './images/projects/mesto.png',
    gif: './images/gif/mesto.gif',
    link_github_page: 'https://gutmalina.github.io/react-mesto-auth/',
    link_github_code: 'https://github.com/gutmalina/react-mesto-auth',
  },
  {
    id: 8,
    type: 'Learn projects',
    name: 'Landing Page Russian Travel',
    about: 'На странице рассказывается о путешествиях по России. Пользователь может посмотреть фотографии, прочитать об интересных фактах, пройдя по ссылкам - получить дополнительную информацию при планировании путешествия.',
    img_bg: './images/flowers/pic3.jpg',
    img_project: './images/projects/russian-travel.png',
    gif: './images/gif/russian-travel.gif',
    link_github_page: 'https://gutmalina.github.io/russian-travel/index.html',
    link_github_code: 'https://github.com/gutmalina/russian-travel',
  },
  {
    id: 9,
    type: 'Test task',
    name: 'Google Books',
    about: 'Приложение для поиска книг в библиотеке Google. Доступен поиск по ключевым словам, сортировка и дополнительная информация о найденных книгах. Выполнена адаптивная вёрстка, использован React + Redux + TypeScript',
    img_bg: './images/flowers/pic10.jpg',
    img_project: './images/projects/books.png',
    gif: './images/gif/google-books.gif',
    link_github_page: 'https://gutmalina.github.io/google-books/',
    link_github_code: 'https://github.com/gutmalina/google-books',
  },
  {
    id: 10,
    type: 'Test task',
    name: 'Landing Page SpaceX',
    about: 'Главная страница сайта компании SpaceX создана в рамках тестового задания. Выполнена адаптивная вёрстка по минимальному макету в формате psd, использован React',
    img_bg: './images/flowers/pic11.jpg',
    img_project: './images/projects/spacex.png',
    gif: './images/gif/spacex.gif',
    link_github_page: 'https://gutmalina.github.io/sagirov_mask/',
    link_github_code: 'https://github.com/gutmalina/sagirov_mask',
  },
  {
    id: 11,
    type: 'Test task',
    name: 'Github Users',
    about: 'Приложение для поиска пользователя в Github. Доступен поиск по имени, сортировка, информация о пользователе, его репозиториях, настроена пагинация, использован React, Router + Rest API + Cypress',
    img_bg: './images/flowers/pic12.jpg',
    img_project: './images/projects/github-users.png',
    gif: './images/gif/github-users.gif',
    link_github_page: 'https://gutmalina.github.io/search-users-github/',
    link_github_code: 'https://github.com/gutmalina/search-users-github',
  },
  {
    id: 12,
    type: 'Pet/commercial projects',
    name: 'Pet project Calculator',
    about: 'Математический калькулятор. Доступны базовые операции, округление до сотых, удаление последнего символа, выполнена вёрстка двух тем (светлая и тёмная).',
    img_bg: './images/flowers/pic13.jpg',
    img_project: './images/projects/calculator.png',
    gif: './images/gif/calculator.gif',
    link_github_page: 'https://gutmalina.github.io/calculator',
    link_github_code: 'https://github.com/gutmalina/calculator',
  },
  {
    id: 13,
    type: 'Test task',
    name: 'Task list',
    about: 'ToDo-приложение, позволяющее управлять текущим списком дел. Доступно добавление, редактирование и удаление задач. Фильтр по дате и список всех задач, с группировкой выполненных и невыполненных задач (по отдельности). Использован React + TypeScript + Cypress',
    img_bg: './images/flowers/pic14.jpg',
    img_project: './images/projects/todos.png',
    gif: './images/gif/todos.gif',
    link_github_page: 'https://gutmalina.github.io/todos/',
    link_github_code: 'https://github.com/gutmalina/todos',
  },
  {
    id: 14,
    type: 'Test task',
    name: 'Data list',
    about: 'SPA приложение-таблица со списком данных. Данные подгружаются по API, настроен онлайн-фильтр, поиск осуществляется по всем столбцам, есть возможность сортировки, вёрстка выполнена согласно макету. Использован React, Router, Bootstrap + Redux, Saga, Toolkit',
    img_bg: './images/flowers/pic15.jpg',
    img_project: './images/projects/data-list.png',
    gif: './images/gif/data-list.gif',
    link_github_page: 'https://gutmalina.github.io/table-sort-filter/',
    link_github_code: 'https://github.com/gutmalina/table-sort-filter',
  },
  {
    id: 15,
    type: 'Pet/commercial projects',
    name: 'Landing Page Interno',
    about: 'Страница компании Interno. Выполнена вёрстка desctop версии для 1440px. Использована методология БЭМ.',
    img_bg: './images/flowers/pic17.jpg',
    img_project: './images/projects/interno.png',
    gif: './images/gif/interno.gif',
    link_github_page: 'https://gutmalina.github.io/Interno/',
    link_github_code: 'https://github.com/gutmalina/Interno',
  },
]
